### ISSUE TITLE
Augment release matrix with binaries for ARM and 32 bit architectures

### ISSUE THREAD

**Issue by olemis** [skycoin/pyskycoin#102]
## Expected Behavior

Binary packages for ARM devices as well as 32 bit architectures should be available for download . 

## Actual Behavior

Installation in aforementiond platforms requires compiling `sdist` packages , which is a complex process.

## Specifications

  - Version: 0.25.0
  - Platform: ARM, 32 bits
  - Subsystem: release

## Possible Solution
Build libskycoin using `GOARCH` and `GOARM` . Optionally , detect architecture . Needs a resolution for skycoin/libskycoin#2

**Comment by olemis** [comment]
@stdevHan the full matrix should be run only while cutting a release . Among ARM architectures , only `orangepi` running on a regular basis .

**Comment by stdevHan** [comment]
@olemis all the others commented work perfectly, the problem is that it would consume a lot of resources from Travis CI.

**Comment by olemis** [comment]
@stdevHan sure ... but the ones commented out should be run for releasing packages to e.g. Github Releases ; so there should be a way to enable /disable , run conditionally

**Comment by stdevMac** [comment]
Solved in c8ed5fdb4223c09057406edc53c07b8ce4646309
