### ISSUE TITLE
Deploy multilinux wheels from Travis to PyPI

### ISSUE THREAD

**Issue by olemis** [skycoin/pyskycoin#107]
## Expected Behavior

While building github tags , deploy script should be triggered and `multilinux` binary wheel packages automatically tested and uploaded onto PyPI .

## Actual Behavior

Deployment script only uploads and all packages onto Github releases and only binary wheels for `osx` end up published in PyPI .

## Specifications

  - Version: 0.25.0
  - Platform: linux
  - Subsystem: travis

## Possible Solution

It seems [PyPI provider](https://docs.travis-ci.com/user/deployment/pypi/) does not fit in the PyPI wheel deployment workflow . Use either [Travis custom deployment](https://docs.travis-ci.com/user/deployment/custom/) or its [script provider](https://docs.travis-ci.com/user/deployment/script/) .

**Comment by stdevMac** [comment]
Solved in ff8ef6bb9e05548615a045d54347869457fcdc0f
