### ISSUE TITLE
Improve README and release procedure

### ISSUE THREAD

**Issue by olemis** [skycoin/pyskycoin#108]
## Expected Behavior

Add in README

- [x] How to building `multilinux` wheels .
- [x] Recent `make dist` family of commands 
- [x] Release signing

## Actual Behavior

Some steps done manually in a way different to instructions in README .

## Specifications

  - Version: 0.25.0
  - Platform: all
  - Subsystem: docs

**Comment by stdevMac** [comment]
Solved in d6f3e202bc0f88a550416332763af8ccc17baf59
