### ISSUE TITLE
Build C library from skycoin/libskycoin

### ISSUE THREAD

**Issue by olemis** [skycoin/pyskycoin#110]
## Expected Behavior

Since Skycoin 0.25.1 the C client library, SWIG, etc are developed in a separate repository (see skycoin/libskycoin#1) . 

- [x] PySkycoin should use code in `skycoin/libskycoin` repository . 
- [x] Describe releationship between project branches and `skycoin/libskycoin` 's
- [x] Two PR's . One for `develop` (#121) and another one for `v0.25.1`

## Actual Behavior

Submodule tracks `skycoin/skycoin@v0.25.0` .

## Specifications

  - Version: 0.25.0
  - Platform: all
  - Subsystem: all

## Possible Solution
Add `skycoin/libskycoin` as submodule and update GOPATH accordingly in `Makefile`, for instance ...

**Comment by stdevMac** [comment]
Solved in 81a0ce79a8440f05c40820b6fbd84d16037cc38b
