### ISSUE TITLE
Update skyapi to latest swagger spec

### ISSUE THREAD

**Issue by stdevMac** [skycoin/pyskycoin#136]
## Expected Behavior
An updated skyapi library according to new swagger spec of Skycoin REST API, can be found here => https://github.com/simelo/libskycoin/blob/stdevMac_t3_v0.25.1_C_Wrapper_Skycoin_Api/lib/swagger/skycoin.v0.25.1.openapi.v2.yml 

## Actual Behavior
Generated python wrapper for Skycoin REST API, for an older swagger spec 

## Possible Solution
Regenerate the library

**Comment by olemis** [comment]
fixed in eb8d93a
