### ISSUE TITLE
Implement CD matrix

### ISSUE THREAD

**Issue by olemis** [skycoin/pyskycoin#139]
**Feature description**

Continuous integration on Circle CI

**Is your feature request related to a problem? Please describe.**
Running a complex matrix build blocks other projects

**Describe the solution you'd like**
Run matrix builds on [Circle CI](https://circleci.com/) . Focus on release since Travis will stil be used for day to day development . If CircleCI usage limits clashes with `libskycoin` builds ( see skycoin/libskycoin#47 ) then choose another service.

**Describe alternatives you've considered**
Travis is not an option . There are all sorts of [Github Apps for CI](https://github.com/marketplace/category/continuous-integration) .

**Additional context**
Related to skycoin/libskycoin#44 .

**Possible implementation**

- [x] Translate `.travis.yml` rules into `CircleCI` script format
- [x] Enable deployment (needs build matrix)

**Comment by stdevMac** [comment]
Solved in c8ed5fdb4223c09057406edc53c07b8ce4646309
