### ISSUE TITLE
[ci] Add Python 3.7 in Travis build matrix

### ISSUE THREAD

**Issue by olemis** [skycoin/pyskycoin#25]
After #18 PySkycoin has support for almost every version of Python in use nowadays, except `3.7` . An [initial attempt](https://github.com/simelo/pyskycoin/blob/d2976e92fbbeb562c961b917c08656e621104fd0/.travis.yml) to add it in the matrix led to [test failure](https://travis-ci.org/simelo/pyskycoin/jobs/401462482) . Therefore it was reverted .

This is issue is for continuing this work until Python 3.7 be added successfully for mac OS and GNU/Linux.

**Comment by olemis** [comment]
test

**Comment by stdevHan** [comment]
test

**Comment by stdevHan** [comment]
test

**Comment by stdevHan** [comment]
test

**Comment by stdevHan** [comment]
@stdevHan @olemis 👍
