### ISSUE TITLE
[docker] Python dev image including Docker daemon

### ISSUE THREAD

**Issue by olemis** [skycoin/pyskycoin#76]
- [x] Image name `skycoindev-python:dind`
- [x] Build FROM `skycoindev-cli:dind`
- [x] Include same tools found in `skycoindev-python:develop` see #12 

Best way to achieve this consists in parameterizing current Dockerfile .

**Comment by stdevYuniers** [comment]
@olemis For do this, a good solution could be parametrize base image to build from either `skycoin/skycoindev-cli:develop` or `skycoindev-cli:dind`. I too could include LABELS.

Tell me what do you think about it.

**Comment by olemis** [comment]
@stdevYuniers both are ok .

**Comment by olemis** [comment]
Always explain how to run `docker` inside the container , please .
