### ISSUE TITLE
Python API wrapper for the Skycoin node API

### ISSUE THREAD

**Issue by olemis** [skycoin/pyskycoin#86]
## Expected Behavior

Access to the Skycoin node REST API implemented in Python code .

## Actual Behavior

Right now this is only possible using code generated by SWIG , which requires memory handles

## Specifications

  - Version: 0.25.0
  - Platform: all
  - Subsystem: all exported API sets

## Possible Solution

~Feel free to use e.g. [requests](https://pypi.org/project/requests/)~

- [x] Use Skycoin node Swagger spec to generate initial Python REST API client
- [x] Add `make` target to automate generation in `./build`
- [x] Aforementioned target should copy / merge relevant files into source code tree
- [x] README explaining the process
- [x] Mention in CHANGELOG
- [x] Patch the result Swagger-gen REST client to support specifying node address
- [x] Update package metadata
- [x] Run basic Swagger tests in Travis
- [x] Unify test code to use either `py.test` (preferred) or `nosetests`
- [x] Beware of CSRF auth

Given the initial commits ...

- [x] Besides rebase initial patch against `0.25.dev` branch

**Comment by olemis** [comment]
@stdevMac it looked like fixed in 1b73050 but I'll have to review whether all items in description above above have been met .

**Comment by olemis** [comment]
@stdevMac unchecked items in description above still not finished . Need them done asap

**Comment by stdevMac** [comment]
@olemis in this last commit is already finished done all the items.

**Comment by olemis** [comment]
fixed by ff67436
